onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /processor_tb/clk
add wave -noupdate /processor_tb/to_mem
add wave -noupdate /processor_tb/dut/core1/bus/ac
add wave -noupdate /processor_tb/dut/core1/bus/busout
add wave -noupdate /processor_tb/dut/core1/bus/dm
add wave -noupdate /processor_tb/dut/core1/bus/dr
add wave -noupdate /processor_tb/dut/core1/bus/im
add wave -noupdate /processor_tb/dut/core1/bus/out
add wave -noupdate /processor_tb/dut/core1/bus/pc
add wave -noupdate /processor_tb/dut/core1/bus/r
add wave -noupdate /processor_tb/dut/core1/bus/read_en
add wave -noupdate /processor_tb/dut/core1/ar/data_in
add wave -noupdate /processor_tb/dut/core1/ar/we
add wave -noupdate /processor_tb/dut/core1/ar/data_out_dm
add wave -noupdate /processor_tb/dut/core1/ar/data_out_im
add wave -noupdate /processor_tb/dut/core1/ar/dm_addr
add wave -noupdate /processor_tb/dut/core1/pc/data_out
add wave -noupdate /processor_tb/dut/core1/pc/inc
add wave -noupdate /processor_tb/dut/core1/r/data_in
add wave -noupdate /processor_tb/dut/core1/r/data_out
add wave -noupdate /processor_tb/dut/core1/r/we
add wave -noupdate /processor_tb/dut/core1/cu/alu_mode
add wave -noupdate /processor_tb/dut/core1/cu/bus_ld
add wave -noupdate /processor_tb/dut/core1/cu/clr
add wave -noupdate /processor_tb/dut/core1/cu/dm_wr
add wave -noupdate /processor_tb/dut/core1/cu/end_op
add wave -noupdate /processor_tb/dut/core1/cu/im_wr
add wave -noupdate /processor_tb/dut/core1/cu/inc
add wave -noupdate /processor_tb/dut/core1/cu/stage
add wave -noupdate /processor_tb/dut/core1/cu/next_stage
add wave -noupdate /processor_tb/dut/core1/cu/prev_stage
add wave -noupdate /processor_tb/dut/core1/cu/write_en
add wave -noupdate /processor_tb/dut/core1/cu/z
add wave -noupdate /processor_tb/dut/data_mem1/r_addr
add wave -noupdate /processor_tb/dut/data_mem1/r_data
add wave -noupdate /processor_tb/dut/data_mem1/w_addr
add wave -noupdate /processor_tb/dut/data_mem1/w_data
add wave -noupdate /processor_tb/dut/data_mem1/we
add wave -noupdate {/processor_tb/dut/data_mem1/mem[150]}
add wave -noupdate /processor_tb/dut/core1/dr/data_in
add wave -noupdate /processor_tb/dut/core1/dr/data_out
add wave -noupdate /processor_tb/dut/core1/dr/we
add wave -noupdate /processor_tb/dut/core1/ir/data_in
add wave -noupdate /processor_tb/dut/core1/ir/data_out
add wave -noupdate /processor_tb/dut/core1/ir/we
add wave -noupdate /processor_tb/dut/core1/ac/clr
add wave -noupdate /processor_tb/dut/core1/ac/data_in
add wave -noupdate /processor_tb/dut/core1/ac/data_out
add wave -noupdate /processor_tb/dut/core1/ac/inc
add wave -noupdate /processor_tb/dut/core1/ac/we
add wave -noupdate /processor_tb/dut/core1/r1/data_in
add wave -noupdate /processor_tb/dut/core1/r1/data_out
add wave -noupdate /processor_tb/dut/core1/r1/we
add wave -noupdate /processor_tb/dut/core1/tr/data_in
add wave -noupdate /processor_tb/dut/core1/tr/data_out
add wave -noupdate /processor_tb/dut/core1/tr/inc
add wave -noupdate /processor_tb/dut/core1/tr/we
add wave -noupdate {/processor_tb/dut/data_mem1/mem[152]}
add wave -noupdate /processor_tb/dut/core1/alu1/alu_out
add wave -noupdate /processor_tb/dut/core1/alu1/in1
add wave -noupdate /processor_tb/dut/core1/alu1/in2
add wave -noupdate /processor_tb/dut/core1/ri/data_out
add wave -noupdate /processor_tb/dut/core1/r1/data_out
add wave -noupdate /processor_tb/dut/core1/r2/data_out
add wave -noupdate /processor_tb/dut/core1/r3/data_out
add wave -noupdate /processor_tb/dut/core1/rj/data_out
add wave -noupdate /processor_tb/dut/core1/rk/data_out
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {4971048 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 270
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {4881142 ps} {5701538 ps}
